import { useMemo, useState } from "react";
import { AUSTRALIA_VISITOR } from "@/lib/rules";

type Analysis = { score:number; summary:string; issues:{severity:string;title:string;detail:string}[]; documents:{name:string;status:string;reason:string}[] };

export default function Home() {
  const [nationality,setNationality] = useState("India"); const [purpose,setPurpose] = useState("Tourism"); const [duration,setDuration] = useState("14"); const [files,setFiles] = useState<File[]>([]); const [analysis,setAnalysis] = useState<Analysis|null>(null); const [loading,setLoading] = useState(false); const [error,setError] = useState("");
  const docs = useMemo(() => files.map(f => ({ name:f.name, type:f.type, size:f.size })), [files]);
  async function analyze() { setLoading(true); setError(""); try { const res=await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({applicant:{nationality,purpose,duration_days:Number(duration)},documents:docs})}); const data=await res.json(); if(!res.ok) throw new Error(data.error||"Analysis failed"); setAnalysis(data); } catch(e:any){setError(e.message)} finally{setLoading(false)} }
  return <main className="shell"><header className="top"><div className="brand">VisaCraft</div><div className="pill">V1 · Application Review</div></header><section className="hero"><div className="eyebrow">Visa application workspace</div><h1>Know what is missing before you submit.</h1><p>Build a structured checklist, add your documents, and let AI surface gaps and inconsistencies. Visa rules remain deterministic; AI is used for interpretation and review.</p></section><div className="grid"><section className="card"><h2>1. Application</h2><div className="muted">V1 starts with Australia Visitor Visa.</div><div className="row"><div className="field"><label className="label">Nationality</label><input className="input" value={nationality} onChange={e=>setNationality(e.target.value)} /></div><div className="field"><label className="label">Purpose</label><select className="select" value={purpose} onChange={e=>setPurpose(e.target.value)}><option>Tourism</option><option>Business</option><option>Visit family</option></select></div></div><div className="field" style={{marginTop:15}}><label className="label">Trip length (days)</label><input className="input" type="number" value={duration} onChange={e=>setDuration(e.target.value)} /></div><div className="drop"><b>2. Drop your visa folder here</b><div className="muted">V1 uses document filenames as the first-pass classifier.</div><input type="file" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))} /></div>{files.length>0&&<div className="result">{files.map(f=><div className="doc" key={f.name}><span>{f.name}</span><span className="status">{Math.round(f.size/1024)} KB</span></div>)}</div>}<button className="btn" style={{marginTop:18,width:"100%"}} disabled={loading} onClick={analyze}>{loading?"Analyzing…":"Analyze application"}</button>{error&&<div className="error">{error}</div>}</section><section className="card"><h2>3. Requirements</h2><div className="muted">Structured source-of-truth for this V1.</div><div className="result">{AUSTRALIA_VISITOR.map(r=><div className="doc" key={r.id}><div><b>{r.title}</b><div className="muted">{r.description}</div></div><span className="status">{r.required?"Required":"Conditional"}</span></div>)}</div></section></div>{analysis&&<section className="card result"><div className="score"><div><div className="eyebrow">AI review</div><h2>{analysis.summary}</h2></div><strong>{analysis.score}</strong></div>{analysis.issues?.map((i,n)=><div className="issue" key={n}><span className="tag">{i.severity.toUpperCase()}</span><b>{i.title}</b><p>{i.detail}</p></div>)}{analysis.documents?.map((d,n)=><div className="issue" key={"d"+n}><span className="tag">{d.status.toUpperCase()}</span><b>{d.name}</b><p>{d.reason}</p></div>)}</section>}<div className="footer">V1 is an application-preparation tool, not legal advice and not a visa-approval predictor. Verify requirements against the relevant official immigration authority before submission.</div></main>
}