
import React, { useState, useRef } from 'react';
import { VisaChecklist } from '../types';

interface ChecklistResultProps {
  checklist: VisaChecklist;
  onReset: () => void;
}

const ChecklistResult: React.FC<ChecklistResultProps> = ({ checklist, onReset }) => {
  const [checkedItems, setCheckedItems] = useState<Record<string, boolean>>({});
  const [isExporting, setIsExporting] = useState(false);
  const checklistRef = useRef<HTMLDivElement>(null);

  const handleExportPDF = async () => {
    const h2p = (window as any).html2pdf;
    if (!h2p) { window.print(); return; }

    setIsExporting(true);

    try {
      // 1. STAGE TO LOCALSTORAGE (Intermediate file simulation)
      const TEMP_KEY = 'visacraft_temp_export';
      localStorage.setItem(TEMP_KEY, JSON.stringify(checklist));

      // 2. RETRIEVE FROM STORAGE
      const storedData = localStorage.getItem(TEMP_KEY);
      if (!storedData) throw new Error('Data staging failed');
      const data: VisaChecklist = JSON.parse(storedData);

      // 3. GENERATE FORMATTED TEMPLATE
      const template = `
        <div style="font-family: 'Helvetica', sans-serif; color: #334155; max-width: 800px; margin: 0 auto;">
          <header style="background: #2563eb; color: white; padding: 40px; border-radius: 12px; margin-bottom: 30px;">
            <h1 style="margin: 0; font-size: 28px; font-weight: 800;">VISA APPLICATION CHECKLIST</h1>
            <p style="margin: 5px 0 0; font-size: 16px; opacity: 0.9;">${data.countryFrom} → ${data.countryTo} | ${data.visaType}</p>
          </header>

          <section style="display: flex; gap: 15px; margin-bottom: 30px;">
            <div style="flex: 1; background: #f8fafc; padding: 15px; border-radius: 8px; border: 1px solid #e2e8f0;">
              <small style="font-weight: 800; font-size: 10px; color: #64748b;">CATEGORY</small>
              <div style="font-weight: 700; margin-top: 4px;">${data.visaCategory}</div>
            </div>
            <div style="flex: 1; background: #f8fafc; padding: 15px; border-radius: 8px; border: 1px solid #e2e8f0;">
              <small style="font-weight: 800; font-size: 10px; color: #64748b;">FEE</small>
              <div style="font-weight: 700; margin-top: 4px;">${data.expectedFee}</div>
            </div>
            <div style="flex: 1; background: #f8fafc; padding: 15px; border-radius: 8px; border: 1px solid #e2e8f0;">
              <small style="font-weight: 800; font-size: 10px; color: #64748b;">DURATION</small>
              <div style="font-weight: 700; margin-top: 4px;">${data.estimatedProcessingTime}</div>
            </div>
          </section>

          <div style="margin-bottom: 30px;">
            <h2 style="font-size: 18px; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px;">Documentation Requirements</h2>
            <ul style="list-style: none; padding: 0;">
              ${[...data.generalRequirements, ...data.specificRequirements].map(r => `
                <li style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; display: flex; align-items: flex-start;">
                  <span style="display: inline-block; width: 18px; height: 18px; border: 2px solid #cbd5e1; margin-right: 12px; border-radius: 4px;"></span>
                  <span>${r}</span>
                </li>
              `).join('')}
            </ul>
          </div>

          <div style="margin-bottom: 30px;">
            <h2 style="font-size: 18px; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px;">Financial Proof</h2>
            <ul style="list-style: none; padding: 0;">
              ${data.financialRequirements.map(r => `
                <li style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; display: flex; align-items: flex-start;">
                  <span style="display: inline-block; width: 18px; height: 18px; border: 2px solid #cbd5e1; margin-right: 12px; border-radius: 4px;"></span>
                  <span>${r}</span>
                </li>
              `).join('')}
            </ul>
          </div>

          <footer style="background: #fdf2f8; border: 1px solid #fce7f3; color: #9d174d; padding: 20px; border-radius: 8px;">
            <h4 style="margin: 0 0 8px 0;">Essential Travel Tips</h4>
            <ul style="margin: 0; padding-left: 20px; line-height: 1.5;">
              ${data.additionalTips.map(t => `<li style="margin-bottom: 4px;">${t}</li>`).join('')}
            </ul>
          </footer>

          <div style="margin-top: 40px; text-align: center; color: #94a3b8; font-size: 11px; border-top: 1px solid #f1f5f9; padding-top: 20px;">
            Official requirements are subject to change. Generated by VisaCraft AI.
          </div>
        </div>
      `;

      // 4. GENERATE AND SAVE PDF
      const opt = {
        margin: [10, 10],
        filename: `Visa_Checklist_${data.countryTo.replace(/\s+/g, '_')}.pdf`,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 2, useCORS: true },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
      };

      await h2p().from(template).set(opt).save();

      // 5. CLEANUP TEMP FILE
      localStorage.removeItem(TEMP_KEY);

    } catch (err) {
      console.error('Data-driven PDF export failed:', err);
      window.print();
    } finally {
      setIsExporting(false);
    }
  };

  const toggleItem = (key: string) => {
    setCheckedItems(prev => ({ ...prev, [key]: !prev[key] }));
  };

  const SummaryCard = ({ label, value, colorClass, borderClass, textClass }: { label: string, value: string, colorClass: string, borderClass: string, textClass: string }) => (
    <div className={`flex-1 min-w-[160px] p-6 rounded-3xl border ${borderClass} ${colorClass} shadow-sm animate-fade-in`}>
      <p className={`text-[10px] font-black uppercase tracking-widest mb-2 ${textClass} opacity-60`}>
        {label}
      </p>
      <p className="text-xl font-black text-slate-800 leading-tight">
        {value}
      </p>
    </div>
  );

  const Section = ({ title, items, icon, colorClass }: { title: string, items: string[], icon: string, colorClass: string }) => (
    <div className="mb-10 animate-fade-in" style={{ animationDelay: '0.1s' }}>
      <div className="flex items-center gap-4 mb-6">
        <div className={`w-12 h-12 rounded-2xl ${colorClass} flex items-center justify-center text-white shadow-lg`}>
          <i className={`fa-solid ${icon} text-lg`}></i>
        </div>
        <h3 className="text-xl font-black text-slate-900 tracking-tight">{title}</h3>
      </div>
      <div className="grid grid-cols-1 gap-4">
        {items.map((item, idx) => {
          const itemKey = `${title}-${idx}`;
          const isChecked = checkedItems[itemKey];
          return (
            <div
              key={itemKey}
              onClick={() => toggleItem(itemKey)}
              className={`flex items-start gap-4 p-5 rounded-[1.25rem] border transition-all cursor-pointer ${isChecked
                ? 'bg-slate-50 border-slate-100 opacity-60'
                : 'bg-white border-slate-100 hover:border-[#005fb0] hover:shadow-md'
                }`}
            >
              <div className={`mt-1 w-6 h-6 rounded-lg flex-shrink-0 border-2 flex items-center justify-center transition-colors ${isChecked
                ? 'bg-[#005fb0] border-[#005fb0] text-white'
                : 'bg-white border-slate-200 text-transparent'
                }`}>
                <i className="fa-solid fa-check text-[10px]"></i>
              </div>
              <p className={`text-base font-medium leading-relaxed ${isChecked ? 'text-slate-500 line-through' : 'text-slate-700'}`}>
                {item}
              </p>
            </div>
          );
        })}
      </div>
    </div>
  );

  return (
    <div className="max-w-4xl mx-auto">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8 no-print">
        <button
          onClick={onReset}
          className="flex items-center gap-2 text-slate-500 hover:text-slate-800 transition-colors font-medium"
        >
          <i className="fa-solid fa-arrow-left"></i>
          Back to Generator
        </button>
        <div className="flex flex-wrap gap-3">
          <button
            onClick={handleExportPDF}
            disabled={isExporting}
            className={`flex items-center justify-center gap-2 px-8 py-3 rounded-2xl font-bold shadow-xl transition-all ${isExporting
              ? 'bg-slate-400 cursor-not-allowed text-white'
              : 'bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white shadow-blue-200 hover:-translate-y-0.5'
              }`}
          >
            {isExporting ? (
              <>
                <i className="fa-solid fa-circle-notch fa-spin"></i>
                Staging Document...
              </>
            ) : (
              <>
                <i className="fa-solid fa-file-pdf"></i>
                Download PDF Checklist
              </>
            )}
          </button>
        </div>
      </div>

      <div
        ref={checklistRef}
        className="checklist-container bg-white border border-slate-100 shadow-2xl rounded-[2rem] mb-12 overflow-hidden animate-fade-in"
      >
        {/* Document Header (Hidden in app, shown in PDF) */}
        <div className="hidden print-only p-8 text-center border-b border-slate-100 bg-slate-50">
          <h1 className="text-2xl font-bold text-slate-900 uppercase tracking-wider">VisaCraft Travel Document</h1>
          <p className="text-slate-500 text-sm mt-1">Personalized Application Checklist & Requirements</p>
        </div>

        <div className="bg-gradient-to-br from-[#005fb0] to-[#001b3e] p-10 md:p-14 text-white">
          <div className="flex flex-wrap items-center gap-3 text-xs font-black uppercase tracking-widest opacity-60 mb-4">
            <span>{checklist.countryFrom}</span>
            <i className="fa-solid fa-arrow-right-long text-[10px]"></i>
            <span>{checklist.countryTo}</span>
          </div>
          <h2 className="text-4xl md:text-5xl font-black mb-6 tracking-tight leading-tight">
            {checklist.visaType} <span className="opacity-50">Checklist</span>
          </h2>
          <div className="flex flex-wrap gap-4 items-center">
            <div className="bg-white/10 backdrop-blur-xl px-5 py-2.5 rounded-2xl flex items-center gap-2 border border-white/10 shadow-lg">
              <i className="fa-solid fa-shield-halved text-blue-300"></i>
              <span className="text-sm font-bold">Verified AI Requirements</span>
            </div>
          </div>
        </div>

        <div className="p-8 md:p-12 border-b border-slate-50 bg-slate-50/30">
          {/* Summary Row */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
            <SummaryCard
              label="Processing"
              value={checklist.estimatedProcessingTime}
              colorClass="bg-white"
              borderClass="border-slate-100"
              textClass="text-[#005fb0]"
            />
            <SummaryCard
              label="Consular Fee"
              value={checklist.expectedFee}
              colorClass="bg-white"
              borderClass="border-slate-100"
              textClass="text-emerald-600"
            />
            <SummaryCard
              label="Legal Category"
              value={checklist.visaCategory}
              colorClass="bg-white"
              borderClass="border-slate-100"
              textClass="text-indigo-600"
            />
          </div>
        </div>

        <div className="p-10 md:p-14">
          {checklist.applicationForms && checklist.applicationForms.length > 0 && (
            <div className="mb-10 p-8 bg-slate-50 border border-slate-100 rounded-[2rem] animate-fade-in shadow-sm">
              <div className="flex items-center gap-4 mb-6">
                <div className="w-12 h-12 rounded-2xl bg-rose-500 flex items-center justify-center text-white shadow-lg">
                  <i className="fa-solid fa-file-pdf text-xl"></i>
                </div>
                <h3 className="text-xl font-black text-rose-900 tracking-tight">Standard Application Forms</h3>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {checklist.applicationForms.map((form, idx) => (
                  <a
                    key={idx}
                    href={form.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center justify-between p-5 bg-white border border-rose-100 rounded-2xl hover:border-rose-400 transition-all group shadow-sm hover:shadow-md"
                  >
                    <div className="flex items-center gap-4">
                      <div className="w-10 h-10 rounded-xl bg-rose-50 flex items-center justify-center text-rose-500 group-hover:bg-rose-500 group-hover:text-white transition-all">
                        <i className="fa-solid fa-cloud-arrow-down"></i>
                      </div>
                      <span className="font-bold text-rose-900">{form.title}</span>
                    </div>
                    <i className="fa-solid fa-chevron-right text-rose-200 group-hover:text-rose-500 transition-colors"></i>
                  </a>
                ))}
              </div>
            </div>
          )}
          <Section
            title="General Documentation"
            items={checklist.generalRequirements}
            icon="fa-file-lines"
            colorClass="bg-[#005fb0]"
          />

          <Section
            title="Specific Visa Requirements"
            items={checklist.specificRequirements}
            icon="fa-suitcase"
            colorClass="bg-indigo-600"
          />

          <Section
            title="Financial Evidence"
            items={checklist.financialRequirements}
            icon="fa-wallet"
            colorClass="bg-amber-600"
          />

          <Section
            title="Expert Travel Advice"
            items={checklist.additionalTips}
            icon="fa-lightbulb"
            colorClass="bg-emerald-600"
          />

          {checklist.officialLinks && checklist.officialLinks.length > 0 && (
            <div className="mt-16 pt-12 border-t border-slate-100 no-print animate-fade-in">
              <h3 className="text-2xl font-black text-slate-900 mb-8 tracking-tight">Official Goverment Portals</h3>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                {checklist.officialLinks.map((link, idx) => (
                  <a
                    key={idx}
                    href={link.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center justify-between p-6 bg-slate-50/50 border border-slate-100 rounded-2xl hover:bg-white hover:border-[#005fb0] transition-all group shadow-sm hover:shadow-lg"
                  >
                    <div className="flex items-center gap-4">
                      <div className="w-12 h-12 rounded-2xl bg-white flex items-center justify-center text-[#005fb0] shadow-sm group-hover:bg-[#005fb0] group-hover:text-white transition-all">
                        <i className="fa-solid fa-building-columns"></i>
                      </div>
                      <span className="font-black text-slate-800 tracking-tight">{link.title}</span>
                    </div>
                    <i className="fa-solid fa-arrow-up-right-from-square text-slate-300 group-hover:text-[#005fb0] transition-colors text-sm"></i>
                  </a>
                ))}
              </div>
            </div>
          )}
        </div>

        <div className="bg-slate-50 border-t border-slate-100 p-6 text-center">
          <p className="text-slate-400 text-xs italic">
            Disclaimer: Requirements can change frequently. Always verify with the official consulate or embassy before your application. Generated by VisaCraft AI.
          </p>
        </div>
      </div>
    </div>
  );
};

export default ChecklistResult;
